Remove path_builder
flexport/svelte pull request #1
Opened 2019-07-19 00:32 UTC by telekid

Svelte is a library that can read a `swagger.json` file and generate rails methods to call endpoints defined within.

In its current form, Svelte's API is fairly verbose when it comes to method calling. For each API operation, it will It autogenerate a module hierarchy based on URL segments. Then, it generates a method at the `operationId` property associated with that given operation.

For example, say `swagger.json` defines the following:
```json
{
  "/api/financing-request/shipment-financing": {
    "post": {
      "summary": "Create a shipment financing request",
      "operationId": "shipment-financing-request"
    }
  }
}
```

Svelte would generate the following method:
```ruby
  Svelte::Service::Capital::Api::FinancingRequest::ShipmentFinancing::shipment_financing_request(body)
```

That is... verbose.

Further, the [swagger spec](https://swagger.io/specification/) mandates that `operationId`s are unique across the API. Therefore, all of that module namespacing is unnecessary and confusing.

This PR turns this:
```ruby
Svelte::Service::Capital::Api::FinancingRequest::ShipmentFinancing::shipment_financing_request(body)
```

Into this:
```ruby
Svelte::Service::Capital.shipment_financing_request(body)
```

...which reads much better to me.

2019-07-22 17:49 UTC, whenceforth requested changes
Seems like a reasonable change, but I'm surprised it didn't break any existing tests.  I'd feel a lot better if you were to add a test for the old code that then needs to be updated with this PR.

Let's chat if that seems infeasible for some reason.

2019-07-29 14:38 UTC, telekid commented
@whenceforth I had forgotten to run `bundle exec rake` 🙈 . Tests were indeed failing.

I've just pushed a commit that fixes tests. LMK if there are additional tests you feel we should add.

New results of `bundle exec rake`:

```text
Svelte::GenericOperation
  #call
    with url parameter
      at the end of the url
        calls Svelte::RestClient with the correct parameters
      not at the end of the url
        calls Svelte::RestClient with the correct parameters
    without url parameters
      calls Svelte::RestClient with the correct parameters
    with missing url parameters
      raises a Svelte::ParameterError exception

Svelte::ModelFactory::Parameter
  is not present when unset
  is present when set
  unset
    appears as unset
  #valid?
    is true when there are no messages
    is false when there are messages
  #as_json
    returns nil if unset
    returns value if set
  validation
    validating a boolean
      when value is not a boolean
        returns a message
      when value is a boolean
        returns no message
    validating a string
      when value is not a string
        returns a message
      when value is a string
        returns no message
    validating a string
      returns no message
    validating a number
      when value is not a number
        returns a message
      when value is a number
        returns no message
    validating an integer
      when value is not an integer
        returns a message
      when value is an integer
        returns no message
    validating an array
      when value is not an array
        returns a message
      when value is an array
        returns no message
        with validatable types
          that are valid
            does not return any errors
          that are invalid
            returns the correct error
    an invalid type
      returns a message
    with permitted values
      when the value is allowed
        returns no message
      when the value is not allowed
        returns a message

ModelFactoryTest
  .define_models
    can load model classes from json
    creates models with the correct dynamic methods
    returns nil if there is a problem
  .define_models_from_json_string
    returns nil if not given something to read
    parses the string if given one
  .define_models_from_file
    returns nil if not given something to read
    reads the file if given one
  .to_json
    returns the results of as_json, JSONized
  .valid?
    with a valid model
      returns true
    with an invalid model
      with required attribute missing
        returns false
      with an attribute set to the wrong type
        returns false
      with an enum attribute set to a non-allowed value
        returns false
  .as_json
    returns a hash representation of the object
    returns nil if the model is empty
  validate
    With Name as a required field
      gives helpful errors
    Without Name as a required field
      Does not include the name field type error even when nil

Svelte::OperationBuilder
  creates a method on the module
  when invoking the method without options
    calls the GenericOperation class when the new method is invoked
  when invoking the method with options
    calls the GenericOperation class when the new method is invoked
  when invoking the method without arguments
    calls the GenericOperation class when the new method is invoked

Svelte::Operation
  has a verb
  has an id
  has a path

Svelte::Path
  paths with no url parameters
    has the correct non parameter elements
    has the correct parameter elements
    #operations
      returns an array of operations
      the array has the correct size
      the array has the correct operations
  paths with url parameters
    has the correct non parameter elements
    has the correct parameter elements
    #operations
      returns an array of operations
      the array has the correct size
      the array has the correct operations

Svelte::RestClient
  should return an http response
  should set optional headers
  when the remote service is very slow
    returns a svelte error to indicate a timeout
  when the remote service is not responding
    returns a svelte error to indicate an http error
  when the resource is not found
    returns a svelte error to indicate a timeout
  when passing a timeout option
    sets up a timeout option on the request

Svelte::StringManipulator
  #constant_name_for
    handles numbers at the beginning
    handles numbers not at the beginning
    handles capitalization at the beginning
    respects existing capitalization
    handles hyphens
    handles numbers and hyphens
    handles numbers at the beginning and somewhere else
    handles names with spaces
    handles names with non alfanumeric characters
  #method_name_for
    transforms simple camel case to snake case
    does not alter snake case
    can handle acronyms at the end of a string
    can handle acronyms at the beginning of a string
    can handle acronyms in the middle of a string
    can handle single capital letters in the middle of a string
    can handle pascal case
    can handle numbers
    handles names with spaces
    handles names with non alfanumeric characters

Svelte
  #create
    with an inline json
      creates the correct module inside Svelte::Service namespace
      creates the operations for each module
    with an online json
      with default options
        creates the correct module inside Svelte::Service namespace
        creates the operations for each module
        raises a Svelte::HTTPException on http errors
      with a bearer token
        sets the correct headers
      with basic authentication
        sets the correct headers
      with arbitrary headers
        sets the correct headers
    with invalid host
      raises a JSONError exception
    with invalid basePath
      raises a JSONError exception
    with invalid paths
      raises a JSONError exception
    with invalid operations
      raises a JSONError exception
    with operations missing mandatory values
      raises a JSONError exception
    with a version 1.2 JSON spec
      raises a VersionError exception

Finished in 0.10834 seconds (files took 0.43798 seconds to load)
99 examples, 0 failures
```

2019-07-30 18:00 UTC, whenceforth approved these changes

2019-07-30 18:08 UTC, merged

2019-07-31 12:34 UTC, AgentAntelope commented
This is really awesome 👍